name: myci

# on 代表触发事件
on: push

# 不写 permissions 的话，在部署时容易出错
permissions:
  contents: write

# 工作流的任务
jobs:
# build 是自定义的名字，可以随意命名
  build:
# 工作流执行的系统环境
    runs-on: ubuntu-latest
    timeout-minutes: 3
# 多策略用法，使用的不多
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
# 工作流执行的具体命令
    steps:
# uses 可以接多种类型，最常用的就是接另一个代码仓库，这里就是一个代码仓库，它的流程就是下载我仓库的代码
    - name: 下载代码
      uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
# 这里的 name 是为 run 起一个名字，会在 GitHub 上显示，也可以不写
    - name: 安装依赖
# run 后边加 | 可以支持写多行脚本
      run: |
        npm install
        npm run build
        npm test -- --watchAll=false
        node -v
    - name: 部署
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: build
# 另一个任务
  work:
    runs-on: ubuntu-latest
# 这个任务用到 nginx 服务
    services:
      nginx:
        image: nginx
        ports:
          - 8080:80
    steps:
    - uses: actions/checkout@v4
    - run: curl localhost:8080
      
